{
  "hash": "08f5201b106474a2ca73860796f0454f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Flight Performance Insights\"\nformat:\n  html:\n    theme: flatly\n    toc: false\n    embed-resources: true\n---\n\n# Introduction\n\nThis project explores patterns in **flight delays, cancellations, and performance** across U.S. airports and airlines. Using SQL on the Bureau of Transportation Statistics (BTS) on-time data set, I extracted insights about:\n\n-   Which airports and days are the busiest\n-   Which locations experience the greatest delays\n-   How cancellations vary by cause\n-   How flight volume changes over time\n\nThe goal is to transform raw flight records into a **clear, data-driven story** about the U.S. air transportation system. Before analyzing flight performance, it’s important to understand the structure and scope of the dataset.\n\n![](https://aviationa2z.com/wp-content/uploads/2024/10/Atlanta-Airport-1.webp){fig-align=\"center\"}\n\n# 1. Understanding the Data\n\nThe dataset contains detailed records on domestic U.S. flights, including departure and arrival times, delays, cancellations, cancellation causes, airline codes, and airport information.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\nlibrary(dplyr)\nlibrary(lubridate)\nlibrary(ggplot2)\nlibrary(treemapify)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nal_perf <- read_csv(\"./data/al_perf.csv\", show_col_types = FALSE)\ndim_airlines <- read_csv(\"data/L_AIRLINE_ID.csv\")\ndim_airports_code <- read_csv(\"data/L_AIRPORT.csv\")\ndim_airports_id <- read_csv(\"data/L_AIRPORT_ID.csv\")\ndim_distance <- read_csv(\"data/L_DISTANCE_GROUP_250.csv\")\ndim_cancel <- read_csv(\"data/L_CANCELATION.csv\")\ndim_weekdays <- read_csv(\"data/L_WEEKDAYS.csv\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary_info <- tibble(\n  Table = c(\"Main Fact Table\", \"Airlines\", \"Airports (Code)\", \"Airports (ID)\",\n            \"Distance Groups\", \"Cancellation Codes\", \"Weekdays\"),\n  Rows = c(nrow(al_perf),\n           nrow(dim_airlines), nrow(dim_airports_code), nrow(dim_airports_id),\n           nrow(dim_distance), nrow(dim_cancel), nrow(dim_weekdays)),\n  Columns = c(ncol(al_perf),\n              ncol(dim_airlines), ncol(dim_airports_code), ncol(dim_airports_id),\n              ncol(dim_distance), ncol(dim_cancel), ncol(dim_weekdays))\n)\n\nsummary_info\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 7 × 3\n  Table                Rows Columns\n  <chr>               <int>   <int>\n1 Main Fact Table    659029     110\n2 Airlines             1665       2\n3 Airports (Code)      6545       2\n4 Airports (ID)        6527       2\n5 Distance Groups        11       2\n6 Cancellation Codes      4       2\n7 Weekdays                8       2\n```\n\n\n:::\n:::\n\n\n| The dataset contains **659,029 flight records** in the main fact table with **110 columns**.\n\nWith a baseline understanding of the dataset, we next examine overall flight activity across airlines and airports. Identifying which carriers and hubs dominate total flight volume provides context for later sections on delays and cancellations, since higher-traffic operators exert more influence on system-wide performance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nal_perf %>%\n  group_by(DOT_ID_Reporting_Airline) %>%\n  summarise(Flights = n()) %>%\n  left_join(dim_airlines, by = c(\"DOT_ID_Reporting_Airline\" = \"ID\")) %>%\n  ggplot(aes(x = reorder(Name, Flights), y = Flights)) +\n  geom_col(fill = \"steelblue\") +\n  coord_flip() +\n  labs(\n    title = \"Total Flights per Airline\",\n    x = \"Airline\",\n    y = \"Number of Flights\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n| The data shows that a small group of carriers accounts for the majority of U.S. flight activity. Southwest, Delta, American, and SkyWest operate substantially more flights than other airlines in the dataset. These high-volume carriers shape the overall performance of the national airspace more than any others.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nal_perf %>%\n  group_by(Origin) %>%\n  summarise(Flights = n()) %>%\n  left_join(dim_airports_code, by = c(\"Origin\" = \"Code\")) %>%\n  arrange(desc(Flights)) %>%\n  slice_head(n = 10) %>%\n  ggplot(aes(x = reorder(Name, Flights), y = Flights)) +\n  geom_col(fill = \"tomato\") +\n  coord_flip() +\n  labs(\n    title = \"Top 10 Busiest Origin Airports\",\n    x = \"Airport\",\n    y = \"Number of Flights\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n| Flight activity is heavily concentrated in a few major hubs, with Atlanta leading by a wide margin. Chicago O’Hare and Dallas/Fort Worth also represent critical high-volume nodes. These airports play a central role in maintaining national traffic flow due to their consistently large departure counts.\n\n# 2. **Delay Patterns & Flight Performance**\n\nAfter understanding where flight activity is concentrated, we explore how reliably these operations perform. This section analyzes departure delays, early departures, and average performance across airlines and airports, highlighting patterns that influence passenger experience and system efficiency.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_departure_delay <- read_csv(\"data/project_q1_bm1262.csv\")\nmax_early_departure <- read_csv(\"data/project_q2_bm1262.csv\")\nweekday_rank <- read_csv(\"data/project_q3_bm1262.csv\")\nairport_max_delay <- read_csv(\"data/project_q4_bm1262.csv\")\nairline_airport_delay <- read_csv(\"data/project_q5_bm1262.csv\")\n```\n:::\n\n\n## 2.1. Maximal Departure Delays per Airline\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_departure_delay %>%\n  top_n(5, MaxDepartureDelayMinutes) %>%\n  ggplot(aes(x = reorder(AirlineName, MaxDepartureDelayMinutes), y = MaxDepartureDelayMinutes)) +\n  geom_col(fill = \"#D55E00\", width = 0.7) +\n  geom_text(aes(label = MaxDepartureDelayMinutes), hjust = -0.1, size = 3.5) +\n  coord_flip() +\n  labs(\n    title = \"Top 5 Airlines with Maximum Departure Delays\",\n    x = \"Airline\",\n    y = \"Max Departure Delay (minutes)\"\n  ) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n| **American Airlines Inc. (AA)** stands out with the longest single departure delay, recorded at **2,347 minutes** (nearly 39 hours).\n\n### Takeaway\n\nMaximum departure delays vary widely by airline, with some carriers experiencing extreme delay events. These outliers highlight operational stress points that can influence reliability perceptions. Even though these delays are not typical, they reveal where irregular operations can be most severe.\n\n### **FAA Context / Implications**\n\n-   **Extreme Outliers:** The **2,347-minute delay** by American Airlines is a critical data point. It represents an exceptional failure in operations, likely due to a major non-routine event such as severe weather combined with crew/aircraft availability issues, or a catastrophic system failure.\n\n-   **Operational Risk:** This chart identifies carriers that have demonstrated an **exposure to extreme, prolonged disruption**. While these events are rare, they are highly consequential for passenger experience, crew legality, and FAA compliance. For a data story, this visual would highlight the *severity* of potential disruptions, contrasting it with the *frequency* or *total volume* of delays.\n\n## 2.2. Maximal Early Departures per Airline\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmax_early_departure %>%\n  mutate(EarlyMinutes = abs(MaxEarlyDepartureMinutes)) %>%  # convert to positive\n  top_n(5, EarlyMinutes) %>%\n  arrange(EarlyMinutes) %>%\n  ggplot(aes(x = reorder(AirlineName, EarlyMinutes), y = EarlyMinutes)) +\n  geom_segment(aes(xend = AirlineName, y = 0, yend = EarlyMinutes), \n               color = \"#0072B2\", size = 1) +\n  geom_point(color = \"#0072B2\", size = 4) +\n  geom_text(aes(label = EarlyMinutes), hjust = -0.3, size = 3.5, color = \"black\") +\n  coord_flip() +\n  labs(\n    title = \"Top 5 Airlines with Largest Early Departures\",\n    subtitle = \"Positive values indicate minutes flights departed early\",\n    x = \"Airline\",\n    y = \"Minutes Early\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, color = \"gray40\"),\n    axis.title = element_text(face = \"bold\"),\n    panel.grid.major.y = element_blank()\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Using `size` aesthetic for lines was deprecated in ggplot2 3.4.0.\nℹ Please use `linewidth` instead.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n| The chart identifies the five airlines that have recorded the **single longest duration of an early departure** (in minutes) within the dataset's period. It focuses on the **maximum extent** to which a flight departed ahead of schedule for each airline.\n\n### Takeaway\n\nSome airlines show a tendency for early departures, with the most extreme cases occurring up to an hour ahead of schedule. These patterns can reflect operational efficiency or differences in scheduling practices. They also demonstrate that timing deviations occur on both ends, not just delays.\n\n### **FAA Context / Implications**\n\n-   **Schedule Padding:** Very large early departures, especially those near or over an hour, may indicate **significant schedule padding** (where extra time is added to the published schedule to improve on-time performance metrics) or a highly unusual, single operational decision to launch a flight far ahead of time (e.g., due to extreme incoming weather).\n\n-   **Passenger Impact:** While not a delay, an excessively early departure is a service failure. It can cause passengers to miss their flight, impacting their travel plans.\n\n-   **Operational Flexibility:** The data suggests that **SkyWest** and **Republic** have, at least once, operated with the greatest amount of scheduling flexibility or have taken the largest operational risk (since very early departures can disrupt gate assignments and air traffic sequencing).\n\n## 2.3. Rank Days of the Week by Flight Volume\n\n\n::: {.cell}\n\n```{.r .cell-code}\nweekday_order <- c(\"Monday\", \"Tuesday\", \"Wednesday\", \"Thursday\", \"Friday\", \"Saturday\", \"Sunday\")\n\nweekday_rank %>%\n  mutate(DayName = factor(DayName, levels = weekday_order)) %>%\n  ggplot(aes(x = DayName, y = NumFlights, group = 1)) +\n  geom_line(color = \"#0072B2\", size = 1.2) +\n  geom_point(color = \"#0072B2\", size = 4) +\n  geom_text(aes(label = NumFlights), vjust = -0.5, size = 3.5) +\n  labs(\n    title = \"Weekly Flight Volume Trend\",\n    subtitle = \"Number of flights by day of the week\",\n    x = \"Day of Week\",\n    y = \"Number of Flights\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, color = \"gray40\"),\n    axis.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n| The chart is a **line chart** titled \"**Weekly Flight Volume Trend**,\" which tracks the aggregate **number of flights** across the seven days of the week.\n\n### Takeaway\n\nFlight volume follows a predictable weekday pattern, with Monday, Tuesday, and Wednesday consistently recording the highest activity. Weekends show a noticeable decline in departures. This distribution indicates stronger business-travel demand during the workweek.\n\n### **FAA Context / Implications**\n\n-   **Peak Demand:** The FAA and air traffic control centers experience the highest sustained demand and workload during the **first three weekdays**. This is crucial for resource planning and managing congestion, as these days likely correspond to high business travel.\n\n-   **Capacity Buffer:** The significant drop in traffic on **Saturdays** provides the greatest **capacity buffer** for maintenance, system upgrades, or handling weather-related recovery without severely impacting the system.\n\n-   **Operational Scheduling:** The trend reflects how the airline industry schedules flights to meet the demand of business and early-week travel, which is important for understanding expected congestion and the timing of delays.\n\n## 2.4. **Airport with the Highest Average Departure Delay**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\n  \"Airport with Highest Average Departure Delay:\\n\",\n  airport_max_delay$AirportName, \"(\", airport_max_delay$AirportCode, \")\\n\",\n  \"Average Delay: \", round(airport_max_delay$AvgDepartureDelay, 1), \"minutes\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAirport with Highest Average Departure Delay:\n Pago Pago, TT: Pago Pago International ( PPG )\n Average Delay:  84.4 minutes\n```\n\n\n:::\n:::\n\n\n| The output directly identifies the airport with the **worst average departure delay performance** across the entire dataset.\n\n### Takeaway\n\nPago Pago International shows the highest average delay across all airports. While this airport has far fewer total flights, its delay values are consistently high. This suggests localized operational challenges rather than system-wide effects.\n\n![](https://i.cdn.newsbytesapp.com/images/l69220240116183655.jpeg){fig-align=\"center\" width=\"651\"}\n\n### **FAA Context / Implications**\n\n-   **Geographic Exception:** Pago Pago's extremely high average delay is a significant outlier, likely due to its **remote location** and unique operational challenges. Flights to and from remote Pacific island territories often involve long-haul carriers, limited daily frequencies, and a dependency on weather/operational conditions that are less flexible than continental U.S. hubs.\n\n-   **Service Quality Metric:** For a data story, this establishes the **upper limit of delay severity** when considering average performance. While major hubs (like ATL or ORD) drive the volume of delays, PPG highlights a critical example of severe, structural performance issues, likely due to low-frequency service and a lack of quick recovery options.\n\n-   **Targeted Investigation:** This finding warrants a deeper investigation into the specific reasons for delays at PPG whether it's weather, crew rest requirements for long flights, or reliance on a single carrier/aircraft for service.\n\n## 2.5. Airport with Highest Average Departure Delay\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_airport_per_airline <- airline_airport_delay %>%\n  group_by(AirlineName) %>%\n  slice_max(AvgDepDelay, n = 1) %>%\n  ungroup()\n\ntop5_airlines <- top_airport_per_airline %>%\n  slice_max(AvgDepDelay, n = 5) %>%\n  arrange(AvgDepDelay)\n\ntop5_airlines %>%\n  ggplot(aes(x = reorder(AirlineName, AvgDepDelay), y = AvgDepDelay)) +\n  geom_segment(aes(xend = AirlineName, y = 0, yend = AvgDepDelay), color = \"#D55E00\", size = 1) +\n  geom_point(color = \"#D55E00\", size = 4) +\n  geom_text(aes(label = round(AvgDepDelay,1)), hjust = -0.3, size = 4) +\n  coord_flip() +\n  labs(\n    title = \"Top 5 Airlines by Maximum Average Departure Delay at a Single Airport\",\n    subtitle = \"One airport per airline with highest average departure delay\",\n    x = \"Airline\",\n    y = \"Average Departure Delay (minutes)\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, color = \"gray40\"),\n    axis.title = element_text(face = \"bold\"),\n    panel.grid.major.y = element_blank()\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\n| The chart shows the **single worst-performing airport** for each airline and then ranks the top five airlines based on that **maximum average delay**. This means the delay shown is **not** the airline's overall average, but their worst-case average at any single airport they serve.\n\n### **Takeaway**\n\nPatterns differ by carrier, with certain airline-airport combinations showing particularly high average delays. These cases point to localized inefficiencies or operational constraints specific to certain routes. They highlight where targeted improvements may be more impactful than broad system-wide changes.\n\n### **FAA Context / Implications**\n\n-   **Structural Failure:** The **505-minute average delay** for ExpressJet at a single airport represents a massive, sustained operational failure at that specific location. This is not a single incident but an **average** over the entire dataset, pointing to a severe, chronic breakdown in scheduling, aircraft turnover, or connectivity at that one hub.\n\n-   **Network Reliability:** For a data story, this visual highlights where **regional carriers** (like ExpressJet, SkyWest, Mesa, and Endeavor) exhibit extreme vulnerability in their networks. Given that regional carriers often feed major hubs, this structural instability can have a major cascading effect on the entire NAS.\n\n-   **Differentiating Metrics:** This chart is critical because it separates **worst-case average performance** from the absolute worst **single event** (as seen in your \"Max Departure Delay\" chart). The average suggests a problem with system *design*, while the single event suggests an operational *anomaly*.\n\n## 3. **Cancellations and Other Flight Metrics**\n\nDelays represent one form of operational disruption, but cancellations often have even greater downstream effects. This section focuses on canceled flights, the frequency of cancellation causes, and the airports where specific disruptions occur most often. These insights help identify systemic weak points within the National Airspace System.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncanceled_flights <- read_csv(\"data/project_q6a_bm1262.csv\")\nmost_freq_cancellation <- read_csv(\"data/project_q6b_bm1262.csv\")\navg_flights_3days <- read_csv(\"data/project_q7_bm1262.csv\")\n```\n:::\n\n\n### 3.1. Total Number of Canceled Flights\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\n  \"Total Number of Canceled Flights in the Dataset:\\n\",\n  canceled_flights$NumCanceledFlights, \"\\n\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal Number of Canceled Flights in the Dataset:\n 12928 \n```\n\n\n:::\n:::\n\n\n| Out of all recorded flights in the dataset, **12,928 flights were canceled**.\n\n### **Takeaway**\n\nThe dataset includes a notable number of canceled flights, confirming that operational disruptions are a regular part of domestic air travel. These cancellations represent a significant source of passenger inconvenience and system-level delays.\n\n### 3.2. **Most Frequent Cancellation Reason per Departure Airport**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntop_cancellations <- most_freq_cancellation %>%\n  group_by(AirportName) %>%\n  slice_max(NumCancellations, n = 1) %>%\n  ungroup() %>%\n  slice_max(NumCancellations, n = 10) %>%\n  arrange(NumCancellations)\n\nggplot(top_cancellations, aes(\n    area = NumCancellations,\n    fill = MostFrequentReason,\n    label = paste0(AirportName, \"\\n\", NumCancellations)\n  )) +\n  geom_treemap(color = \"white\", size = 0.5) +\n  geom_treemap_text(\n    fontface = \"bold\",\n    colour = \"white\",\n    place = \"centre\",\n    grow = TRUE,\n    reflow = TRUE\n  ) +\n  scale_fill_brewer(palette = \"Set2\") +\n  labs(\n    title = \"Top 10 Airports by Most Frequent Cancellation Reason\",\n    subtitle = \"Area represents number of cancellations; color indicates reason\"\n  ) +\n  theme_minimal(base_size = 14) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, color = \"gray40\"),\n    legend.title = element_text(face = \"bold\")\n  )\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n| The visual is a **Treemap** that shows the **Top 10 Airports** ranked by their total number of flight cancellations. The **size** of each rectangular tile corresponds to the total number of cancellations at that airport, and the **color** represents the single most frequent reason for cancellation at that airport (either **National Air System** or **Weather**).\n\n### **Takeaway**\n\n1.  **Chicago O'Hare (ORD)** has the highest volume of cancellations (**511**), and its dominant reason is the **National Air System** (NAS - green).\n\n2.  **Weather** (orange) is the most frequent cancellation cause for many major hubs, including **New York LaGuardia (LGA)**, **Dallas/Fort Worth (DFW)**, **Newark Liberty (EWR)**, and **Denver (DEN)**.\n\n3.  The top two cancellation airports ORD and DFW/LGA (tied for the next rank) are split between a dominant NAS cause and a dominant Weather cause, pointing to different core problems at these major hubs.\n\n![Chicago O'Hare International Airport](https://s28477.pcdn.co/wp-content/uploads/2018/01/ORD_1-984x554.jpg){fig-align=\"center\"}\n\n### **FAA Context / Implications**\n\n-   **Systemic vs. Environmental Issues:** The visualization clearly separates cancellation drivers. Airports dominated by the **NAS** reason (like ORD) suggest problems are **systemic** (e.g., equipment failure, air traffic control, heavy traffic congestion, operational decisions), which the FAA can potentially control or mitigate with infrastructure and procedural changes.\n\n-   **Weather Vulnerability:** Airports dominated by **Weather** (like LGA, DFW, and EWR) indicate a high vulnerability to environmental factors. For these hubs, strategies should focus on **weather forecasting accuracy**, quick **recovery procedures**, and better **diversion management**. This contrast is essential for building a data-driven story about where intervention is most effective.\n\n### 3.3. Average Number of Flights Over The Preceding 3 Days\n\nTo understand how flight activity evolves over time, we examine a 3-day rolling average of national flight volume. This smooths out daily fluctuations and reveals broader temporal patterns such as weekday cycles or holiday drops that influence staffing, resource allocation, and airspace planning.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(avg_flights_3days, aes(x = as.Date(FlightDate), y = AvgFlightsPrev3Days)) +\n  geom_line(color = \"#0072B2\", size = 1.2) +\n  geom_point(color = \"#D55E00\", size = 2, alpha = 0.7) +\n  labs(\n    title = \"3-Day Moving Average of Daily Flights\",\n    subtitle = \"Smooth trend showing average number of flights over the preceding 3 days\",\n    x = \"Date\",\n    y = \"Average Number of Flights\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(\n    plot.title = element_text(face = \"bold\", size = 16),\n    plot.subtitle = element_text(size = 12, color = \"gray40\")\n  ) +\n  geom_vline(xintercept = as.Date(\"2019-07-04\"), linetype = \"dashed\", color = \"gray40\") +\n  annotate(\"text\", x = as.Date(\"2019-07-04\"), y = max(avg_flights_3days$AvgFlightsPrev3Days),\n           label = \"July 4th Holiday\", vjust = -0.5, hjust = 0.5, color = \"gray20\", size = 3.5)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n| The visual is a **line chart** that uses a 3-day **moving average** to smooth out daily fluctuations and show the underlying trend in air traffic volume across the month of July.\n\n### **Takeaway**\n\nThe rolling average smooths daily fluctuations and highlights underlying traffic patterns. The trend shows consistent weekday peaks with holiday-related dips, revealing predictable cycles in national airspace demand. This time-series view provides context for staffing and resource planning.\n\n### **FAA Context / Implications**\n\n-   **Holiday Impact:** The July 4th drop demonstrates that **major national holidays** temporarily cause a substantial reduction in commercial air traffic, likely due to a sharp decline in business travel coinciding with a major leisure travel period where travel days shift away from the holiday itself.\n\n-   **Systemic Load Cycles:** The regular weekly peaks show the consistent high load periods the National Airspace System (NAS) must manage. These **mid-week peaks** are the times when the system is most stressed and most vulnerable to delays. The weekend dip provides a consistent, albeit brief, **operational recovery period**.\n\n-   **Smoothing Data:** By using a 3-day moving average, the chart effectively filters out noise to highlight these two major trends: the predictable **weekly cycle** and the acute impact of the **holiday anomaly**.\n\n## 4. Key Insights\n\nAfter reviewing volume, delays, cancellations, and temporal patterns, we consolidate the major findings. This section summarizes the operational significance of the observed trends and discusses what they imply for efficiency, passenger experience, and FAA resource management.\n\n### 4.1. Operational Insights: Dominance and Vulnerability\n\nThe analysis of flight volume and performance metrics reveals that the air travel system's success or failure is concentrated among a few major players and is highly exposed to chronic issues within specific segments.\n\n-   **Dominance of Major Carriers and Hubs:** The top four airlines (**Southwest, Delta, American, and SkyWest**) and the top three airports (**Atlanta-ATL, Chicago-ORD, and Dallas/Fort Worth-DFW**) completely dominate the system by **flight volume**. Their performance directly dictates the overall efficiency of the National Airspace System (NAS). Disruptions at these few points have the largest cascading effect nationwide.\n\n-   **Extreme Delay Exposure in Regional Carriers:** While major carriers fly the most, **regional carriers** (ExpressJet, SkyWest, Mesa, and Envoy) show an alarming exposure to extreme delays. ExpressJet, in particular, recorded a maximum average departure delay of **505 minutes** at a single airport a finding that suggests a **structural failure** or chronic operational bottleneck rather than a simple anomaly.\n\n![SkyWest Jet](https://t.plnspttrs.net/32791/1381081_11298dbb38_280.jpg){fig-align=\"center\"}\n\n-   **Cancellation Drivers are Bifurcated:** High-volume cancellations at major hubs are caused by two distinct factors:\n\n    -   **National Air System (NAS)**: Dominant at airports like **Chicago O'Hare (ORD)**, suggesting issues related to air traffic control, runway capacity, or equipment that the FAA can directly address.\n\n    -   **Weather**: Dominant at airports like **Newark (EWR)** and **Dallas/Fort Worth (DFW)**, indicating high vulnerability to environmental conditions where mitigation must focus on swift recovery protocols.\n\n### 4.2. FAA Resource Allocation, Efficiency, and Passenger Experience\n\nThe data provides a clear roadmap for where the FAA and carriers should focus their resources to maximize efficiency and minimize passenger inconvenience.\n\n-   **Resource Prioritization:** FAA resources (staffing, air traffic control technology, etc.) should be overwhelmingly prioritized at the **top 10 busiest origin airports** and during the **peak travel days** (Monday through Wednesday) to manage congestion and prevent delays from escalating.\n\n-   **Efficiency vs. Padding:** The large range in departure scheduling from the extreme delay of **2,347 minutes** (American Airlines) to the maximum early departure of **66 minutes** (SkyWest) suggests high inconsistency in operations. While early departures suggest schedule padding, the extreme delays indicate an urgent need to improve robust contingency planning and response protocols.\n\n-   **Service Quality Outliers:** The remote location of **Pago Pago (PPG)** having the highest average departure delay (**84.4 minutes**) highlights a critical service quality issue in low-frequency, long-haul routes. The FAA must consider the unique challenges of non-continental U.S. air service.\n\n### 4.3. Clear Temporal and Geographic Patterns\n\nPredictable cycles and geographic differences offer opportunities for proactive management rather than reactive responses.\n\n-   **Weekly Cycle:** Air traffic demand is highly predictable, peaking consistently from **Monday to Wednesday** and dipping significantly on **Saturday** (the lowest volume day). This Saturday drop offers the greatest window for scheduled maintenance and non-urgent system upgrades.\n\n-   **Holiday Impact:** Major holidays, such as **July 4th**, cause a deep, short-term reduction in overall flight volume, offering a predictable, though short, system lull.\n\n-   **Geographic Vulnerability:** The analysis of cancellations shows that the type of problem is geographically distinct: cold-weather/congestion hubs (ORD) battle NAS issues, while others (DFW, EWR) are primarily battling weather. This requires geographically tailored solutions rather than a one-size-fits-all approach to cancellation management.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}